# Generated by Django 3.2 on 2023-10-17 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basename', models.CharField(max_length=200, unique=True, verbose_name='Базовое имя')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Уникальный слаг')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Уникальный слаг')),
                ('basename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_variants', to='gachi.basename', verbose_name='Базовое имя')),
            ],
        ),
        migrations.CreateModel(
            name='Gachi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gachi', models.CharField(max_length=200, verbose_name='Гача')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gachies', to='gachi.name', verbose_name='Имя')),
            ],
        ),
    ]
