# Generated by Django 3.2 on 2023-10-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gachi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
    ]
